
(format t "~{~&\"org.openscience.cdk/cdk-~A/2.2-SNAPSHOT\"~}"
        '("annotation"
          #+(or) "app"
          "atomtype"
          #+(or) "base"
          "builder3d"
          "builder3dtools"
          "bundle"
          "charges"
          "cip"
          "control"
          "core"
          "ctab"
          "data"
          "datadebug"
          "depict"
          #+(or) "descriptor"
          "dict"
          "diff"
          #+(or) "display"
          "extra"
          "fingerprint"
          "forcefield"
          "formula"
          "fragment"
          "group"
          "hash"
          "inchi"
          "interfaces"
          "io"
          "ioformats"
          "ionpot"
          "iordf"
          "isomorphism"
          "legacy"
          "libiocml"
          "libiomd"
          "log4j"
          #+(or) "misc"
          "model"
          "pcore"
          "pdb"
          "pdbcml"
          "qm"
          "qsar"
          "qsaratomic"
          "qsarbond"
          "qsarcml"
          "qsarionpot"
          "qsarmolecular"
          "qsarprotein"
          "qsarsubstance"
          "reaction"
          "render"
          "renderawt"
          "renderbasic"
          "renderextra"
          "sdg"
          "signature"
          "smarts"
          "smiles"
          "smsd"
          "standard"
          #+(or) "storage"
          "structgen"
          "tautomer"
          "testdata"
          #+(or) "tool"
          "valencycheck"))
